### ISSUE TITLE
Sample code doesn't work 

### ISSUE THREAD

**Issue by sandeeprawat** [merijndejonge/Structurizr.Dgml#1]
ToDgml extension method doesn't work with 1.9 or 1.12 OpenSoftware.DgmlBuilder

Older version of library don't have WriteToFile extension method.

Can you update the sample and the project please?

**Comment by merijndejonge** [comment]
HI,
Sorry for the inconvenience.
I've uploaded a new version of the Structurizr.Dgml nuget pacakge (1.2.1). It should be available for download from nuget.org soon.
I've also updated the example in the README.
Please let me know if that solves your issue.

**Comment by sandeeprawat** [comment]
(y) Looks good now. Thanks for the quick turnaround.
