### ISSUE TITLE
Could not load type 'Structurizr.Taggable' from assembly 'Structurizr.Core, Version=0.9.0.0

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [merijndejonge/Structurizr.Dgml#2]
Hi,

I am trying to create a small example of a Dgml using the most recent nuget packages and am getting:

Could not load type 'Structurizr.Taggable' from assembly 'Structurizr.Core, Version=0.9.0.0

When I call:
var dgml = workspace.ToDgml();

I received a response on the structurizr github: https://github.com/structurizr/dotnet/issues/39

Example Code is:

		Workspace workspace = new Workspace("Getting Started", "This is a model of my software system.");
		Model model = workspace.Model;

		Person user = model.AddPerson("User", "A user of my software system.");
		SoftwareSystem softwareSystem = model.AddSoftwareSystem("Software System", "My software system.");
		user.Uses(softwareSystem, "Uses");

		ViewSet viewSet = workspace.Views;
		SystemContextView contextView = viewSet.CreateSystemContextView(softwareSystem, "SystemContext", "An example of a System Context diagram.");
		contextView.AddAllSoftwareSystems();
		contextView.AddAllPeople();

		Styles styles = viewSet.Configuration.Styles;
		styles.Add(new ElementStyle(Tags.SoftwareSystem) { Background = "#1168bd", Color = "#ffffff" });
		styles.Add(new ElementStyle(Tags.Person) { Background = "#08427b", Color = "#ffffff", Shape = Shape.Person });

		// Convert to DGML
		var dgml = workspace.ToDgml();
		// Write to file
		dgml.WriteToFile("example.dgml");

**Comment by merijndejonge** [comment]
I changed Structurizr.Taggable to Structurizr.ModelItem and uploaded a new version (1.2.2) to nuget.org.
@Michael-Tajmajer-Emrsn Can you please update and check if it now works for you.
Thanks for reporting the issue.
